# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Build the iOS app"
  lane :build do
    gym(
      scheme: "Runner",    # Replace with your scheme
      configuration: "Release",   # or Debug
      export_method: "development", # Or other method like "app-store", "ad-hoc", etc.
      output_directory: "build",  # Directory to save the build output
      output_name: "flutter_app.ipa"  # Name of the output file
    )
  end

  desc "Take screenshots of the iOS app"
  lane :screenshots do
    capture_screenshots(
      devices: ["iPhone 14 Pro", "iPhone 14"],
      languages: ["en-US"]                    
    )
  end
end
